new configure option "--enable-redhat-systemd" for Fedora15 and later. "--enable-redhat" is renamed "--enable-redhat-sysv". suggested by netatalk-2.2.0-4.fc17.src.rpm

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -385,13 +385,29 @@ AC_ARG_ENABLE(locking,
 
 )
 
-
 AC_ARG_ENABLE(redhat,
-	[  --enable-redhat         use redhat-style sysv configuration ],[
+	[  --enable-redhat         obsoleted ],[
+	echo "ERROR: --enable-redhat is obsoleted. Use --enable-redhat-sysv or --enable-redhat-systemd."
+	echo "exit 1"
+	exit 1
+	]
+)
+
+AC_ARG_ENABLE(redhat-sysv,
+	[  --enable-redhat-sysv    use redhat-style sysv (upstart) configuration ],[
 	if test "$enableval" = "yes"; then
-		sysv_style=redhat
+		sysv_style=redhat-sysv
 	fi
 	AC_MSG_RESULT([enabling redhat-style sysv support])
+	]
+)
+
+AC_ARG_ENABLE(redhat-systemd,
+	[  --enable-redhat-systemd use redhat-style systemd (>=Fedora15) configuration ],[
+	if test "$enableval" = "yes"; then
+		sysv_style=redhat-systemd
+	fi
+	AC_MSG_RESULT([enabling redhat-style systemd support])
 	]
 )
 
@@ -1261,7 +1277,8 @@ AM_CONDITIONAL(BUILD_PAM, test x$compile_pam = xyes)
 AM_CONDITIONAL(USE_PGP, test x$compile_pgp = xyes)
 AM_CONDITIONAL(DEFAULT_HOOK, test x$neta_cv_have_libgcrypt != xyes && test x$neta_cv_have_openssl != xyes)
 AM_CONDITIONAL(USE_NETBSD, test x$sysv_style = xnetbsd)
-AM_CONDITIONAL(USE_REDHAT, test x$sysv_style = xredhat)
+AM_CONDITIONAL(USE_REDHAT_SYSV, test x$sysv_style = xredhat-sysv)
+AM_CONDITIONAL(USE_REDHAT_SYSTEMD, test x$sysv_style = xredhat-systemd)
 AM_CONDITIONAL(USE_SUSE, test x$sysv_style = xsuse)
 AM_CONDITIONAL(USE_SHADOWPW, test x$shadowpw = xyes)
 AM_CONDITIONAL(USE_TRU64, test x$sysv_style = xtru64)
