RedHat's initscript: Any daemon did not run if atalkd doesn't exist.

diff --git a/distrib/initscripts/rc.atalk.redhat.tmpl b/distrib/initscripts/rc.atalk.redhat.tmpl
--- a/distrib/initscripts/rc.atalk.redhat.tmpl
+++ b/distrib/initscripts/rc.atalk.redhat.tmpl
@@ -39,21 +39,16 @@ atalk_startup() {
          exit 1;
     fi
 
-    if [ ! -x ${ATALK_SBIN}/atalkd ]; then
-         # Quickly probe for appletalk and warn if we can't find it
-         #/sbin/modprobe appletalk || echo "[could not load appletalk module]"
-         # Check for IP Encapsulation support
-         #/sbin/modprobe ipddp || echo "[could not load IP encapsulation]"
-         echo "[${ATALK_SBIN}/atalkd not found. Check for permissions]";
-         exit 4;
-    fi
-
     if [ ! -f ${ATALK_CONF_DIR}/netatalk.conf ]; then
          echo "[${ATALK_CONF_DIR}/netatalk.conf not found]";
          exit 6;
     fi
 
-    if [ x"${ATALKD_RUN}" != x"no" ]; then 
+    if [ x"${ATALKD_RUN}" != x"no" -a -x ${ATALK_SBIN}/atalkd ]; then 
+         # Quickly probe for appletalk and warn if we can't find it
+         #/sbin/modprobe appletalk || echo "[could not load appletalk module]"
+         # Check for IP Encapsulation support
+         #/sbin/modprobe ipddp || echo "[could not load IP encapsulation]"
 	echo -n "  Starting atalkd:"
 	daemon ${ATALK_SBIN}/atalkd
 	RETVAL_ATALKD=$?
