Once again rework cnid_metad logging setup code and config. Checked in the according manpages too. Also fixed: downstream Debian patches to their init script.

diff --git a/distrib/initscripts/rc.atalk.debian.tmpl b/distrib/initscripts/rc.atalk.debian.tmpl
--- a/distrib/initscripts/rc.atalk.debian.tmpl
+++ b/distrib/initscripts/rc.atalk.debian.tmpl
@@ -1,32 +1,50 @@
 #!/bin/sh
+### BEGIN INIT INFO
+# Provides:          netatalk
+# Required-Start:    $remote_fs $syslog
+# Required-Stop:     $remote_fs $syslog
+# Default-Start:     2 3 4 5
+# Default-Stop:      1
+### END INIT INFO
 #
-# atalk         Netatalk 2.x initscript
-#
+# netatalk      Netatalk 2.x initscript
 # Author:       Thomas Kaiser <Thomas.Kaiser@phg-online.de>
-#
-# Version:      $Id: rc.atalk.debian.tmpl,v 1.5 2009-05-19 11:56:23 franklahm Exp $
+# Version:      $Id: rc.atalk.debian.tmpl,v 1.6 2009-06-09 11:58:49 franklahm Exp $
 
 set -e
 
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 DESC="Netatalk"
-NAME=atalk
+NAME=netatalk
 SCRIPTNAME=/etc/init.d/$NAME
 
 # Guard to prevent execution if netatalk was removed.
 test -x :SBINDIR:/atalkd || exit 0
 
+# Set defaults. Please change these options in /etc/default/netatalk
+AFPD_UAMLIST="-U uams_dhx2.so"
+AFPD_GUEST=nobody
+AFPD_MAX_CLIENTS=50
+ATALK_ZONE=
+ATALK_NAME=`/bin/hostname --short`
+ATALK_BGROUND=no
+CNID_METAD_RUN=yes
+ATALK_MAC_CHARSET='MAC_ROMAN'
+ATALK_UNIX_CHARSET='LOCALE'
+
 # Read in netatalk configuration.
-if [ -f :ETCDIR:/netatalk.conf ]; then
-	. :ETCDIR:/netatalk.conf
+if [ -f /etc/default/netatalk ]; then
+    . /etc/default/netatalk
 fi
 
 # Start Netatalk servers.
 atalk_startup() {
 	if [ x"$ATALKD_RUN" = x"yes" ]; then
 
-	# Try to load the AppleTalk kernel module
-	/sbin/modprobe appletalk || echo "[could not load appletalk module]"
+	# Try to load the AppleTalk kernel module if it was intended.
+    if grep -q '^appletalk$' /etc/modules; then
+        /sbin/modprobe appletalk || echo "[could not load appletalk module]"
+    fi
 
 	# Start atalkd server.
 	:SBINDIR:/atalkd
@@ -39,13 +57,9 @@ atalk_startup() {
 	fi
 	
 	# prepare startup of file services
-	if [ x"${CNID_METAD_RUN}" = x"yes" -a -x :SBINDIR:/cnid_metad ] ; then
+	if [ "x$CNID_METAD_RUN" = "xyes" -a -x :SBINDIR:/cnid_metad ] ; then
 		echo -n " cnid_metad"
-        if [ "x$CNID_DBD_LOGCONFIG" = "x" ]; then
-            :SBINDIR:/cnid_metad
-        else
-            :SBINDIR:/cnid_metad -l "$CNID_DBD_LOGCONFIG"
-        fi
+        :SBINDIR:/cnid_metad $CNID_CONFIG
     fi
 	
 	if [ x"$AFPD_RUN" = x"yes" ]; then
@@ -54,20 +68,22 @@ atalk_startup() {
 	echo -n " afpd"
 	fi
 
-	if [ x"$ATALKD_RUN" = x"yes" -a x"$PAPD_RUN" = x"yes" ]; then
-	:SBINDIR:/papd
-	echo -n " papd"
-	fi
+    if [ "x$ATALKD_RUN" = "xyes" ]; then
+        if [ "x$PAPD_RUN" = "xyes" ]; then
+            :SBINDIR:/papd
+            echo -n " papd"
+        fi
 
-	if [ x"$TIMELORD_RUN" = x"yes" ]; then
-	:SBINDIR:/timelord
-	echo -n " timelord"
-	fi
+        if [ x"$TIMELORD_RUN" = x"yes" ]; then
+            :SBINDIR:/timelord
+            echo -n " timelord"
+        fi
+    fi
 }
 
 case "$1" in
 	start)
-		if test x"${ATALK_BGROUND}" = x"yes"; then
+		if test "x$ATALK_BGROUND" = "xyes"; then
 			echo "Starting Netatalk services in the background."
 			atalk_startup >/dev/null &
 		else
