don't load atalkd kernel module, either appletalk is not compiled or it will be loaded automatically, from HAT

diff --git a/distrib/initscripts/rc.atalk.redhat.tmpl b/distrib/initscripts/rc.atalk.redhat.tmpl
--- a/distrib/initscripts/rc.atalk.redhat.tmpl
+++ b/distrib/initscripts/rc.atalk.redhat.tmpl
@@ -19,13 +19,11 @@ ATALK_SBIN=:SBINDIR:
 # Source networking configuration.
 . /etc/sysconfig/network
 
-# Quickly probe for appletalk and warn if we can't find it
-/sbin/modprobe appletalk || echo "[could not load appletalk module]"
-
-# Check for IP Encapsulation support
-#/sbin/modprobe ipddp || echo "[could not load IP encapsulation]"
-
 if [ ! -x ${ATALK_SBIN}/atalkd ]; then
+     # Quickly probe for appletalk and warn if we can't find it
+     #/sbin/modprobe appletalk || echo "[could not load appletalk module]"
+     # Check for IP Encapsulation support
+     #/sbin/modprobe ipddp || echo "[could not load IP encapsulation]"
      echo "[${ATALK_SBIN}/atalkd not found.  Did it compile?]";
      exit 0;
 fi
