Fix a problem with the PAM install.

diff --git a/config/Makefile.am b/config/Makefile.am
--- a/config/Makefile.am
+++ b/config/Makefile.am
@@ -52,8 +52,7 @@ pamdir = @PAMDIR@/etc/pam.d
 install-data-local: install-config-files $(PAMFILES)
 	$(mkinstalldirs) $(DESTDIR)$(pamdir)
 	for f in $(PAMFILES); do					\
-		$(INSTALL_DATA) $$f $(DESTDIR)$(pamdir)/netatalk ||	\
-			echo "WARNING: Can't install PAM files"		\
+		$(INSTALL_DATA) $$f $(DESTDIR)$(pamdir)/netatalk || echo "WARNING: Can't install PAM files"		\
 	done
 
 else
